# -*- coding: utf-8 -*-
"""a3a draft 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Oo7eb-KOwDZb0Ix_cBrfsXThubDhFnY
"""

!pip install -q fastapi "uvicorn[standard]" requests cohere python-multipart

import os
from getpass import getpass

cohere_key = getpass("Enter your Cohere API Key: ")
a2a_key = getpass("Enter a shared A2A secret (X-A2A-KEY): ")

os.environ['COHERE_API_KEY'] = cohere_key
os.environ['A2A_API_KEY'] = a2a_key
# choose a chat-capable model you have access to
os.environ['COHERE_MODEL'] = "command-a-03-2025"

print("Keys set for session (hidden).")

import os, json
import cohere

COHERE_API_KEY = os.environ.get('COHERE_API_KEY')
if not COHERE_API_KEY:
    raise RuntimeError("COHERE_API_KEY missing - run secret cell first.")

co = cohere.ClientV2(api_key=COHERE_API_KEY)
COHERE_MODEL = os.environ.get('COHERE_MODEL', 'command-a-03-2025')
print("Cohere Client ready. Model:", COHERE_MODEL)

# quick chat test (will raise if auth/model wrong)
res = co.chat(model=COHERE_MODEL, messages=[{"role":"system","content":"You are a test assistant."},{"role":"user","content":"Say hi"}], max_tokens=8)
print("Cohere test ok:", res.message.content[0].text)

# Utilities used by multiple agents
import json, uuid, hmac, hashlib, os

A2A_KEY = os.environ.get('A2A_API_KEY')
if not A2A_KEY:
    raise RuntimeError("A2A_API_KEY missing. Run secret cell first.")

def make_agent_card(name, version, port, methods):
    card = {
        "agent_id": f"{name.lower()}-{str(uuid.uuid4())[:8]}",
        "name": name,
        "version": version,
        "endpoint": f"http://127.0.0.1:{port}/rpc",
        "methods": methods
    }
    # also write to disk for discovery
    with open(f"agent_card_{name.lower()}.json", "w") as f:
        json.dump(card, f, indent=2)
    return card

def require_auth(headers):
    key = headers.get('x-a2a-key') or headers.get('X-A2A-KEY') or headers.get('X-A2A-Key')
    return key == A2A_KEY

def jsonrpc_success(id_, result):
    return {"jsonrpc":"2.0","id": id_,"result": result}

def jsonrpc_error(id_, code, message):
    return {"jsonrpc":"2.0","id": id_,"error": {"code": code,"message": message}}

# WeatherAgent on port 8102 (example)
from fastapi import FastAPI, Request
from pydantic import BaseModel
import uvicorn
import json

WEATHER_PORT = 8102
weather_app = FastAPI()
WEATHER_CARD = make_agent_card("WeatherAgent","0.1", WEATHER_PORT, ["get_weather","get_weather_structured"])

@weather_app.get("/a2a/agent-card")
async def agent_card():
    return WEATHER_CARD

@weather_app.post("/rpc")
async def rpc(req: Request):
    body = await req.json()
    # auth
    if not require_auth(req.headers):
        return jsonrpc_error(body.get("id"), -32600, "unauthorized: missing/invalid X-A2A-KEY")
    method = body.get("method")
    params = body.get("params", {})
    rid = body.get("id")
    try:
        if method == "get_weather":
            city = params.get("city"); date = params.get("date")
            # deterministic mock
            rain = (len(city)*13 + len(date)) % 70
            txt = f"Mock weather for {city} on {date}: {rain}% chance of rain."
            return jsonrpc_success(rid, {"text": txt})
        elif method == "get_weather_structured":
            city = params.get("city"); date = params.get("date")
            rain = (len(city)*13 + len(date)) % 70
            structured = {
                "city": city, "date": date,
                "condition": "rain" if rain>40 else "clear",
                "temp_c": 25 + (len(city) % 5),
                "chances_of_precipitation": rain,
                "advice": "Carry umbrella" if rain>40 else "Sunglasses recommended"
            }
            return jsonrpc_success(rid, {"structured": structured})
        else:
            return jsonrpc_error(rid, -32601, f"method not found: {method}")
    except Exception as e:
        return jsonrpc_error(rid, -32000, f"internal error: {e}")

# function to run in background thread
def run_weather():
    uvicorn.run(weather_app, host="127.0.0.1", port=WEATHER_PORT, log_level="info")

from fastapi import FastAPI, Request
import uvicorn, requests, json, os

PLANNER_PORT = 8103
planner_app = FastAPI()
PLANNER_CARD = make_agent_card("PlannerAgent","0.1", PLANNER_PORT, ["plan_from_weather","plan_from_structured"])

# simple helper: call agent JSON-RPC
def call_agent(endpoint, method, params):
    payload = {"jsonrpc":"2.0","id": str(uuid.uuid4()), "method": method, "params": params}
    headers = {"Content-Type":"application/json","X-A2A-KEY": os.environ['A2A_API_KEY']}
    r = requests.post(endpoint, json=payload, headers=headers, timeout=10)
    return r.json()

@planner_app.get("/a2a/agent-card")
async def agent_card():
    return PLANNER_CARD

@planner_app.post("/rpc")
async def rpc(req: Request):
    body = await req.json()
    if not require_auth(req.headers):
        return jsonrpc_error(body.get("id"), -32600, "unauthorized")
    method = body.get("method"); params = body.get("params", {}); rid = body.get("id")
    try:
        if method == "plan_from_weather":
            city = params.get("city"); start = params.get("start_date"); n_days = params.get("n_days",2)
            # call WeatherAgent for summaries
            weather_texts = []
            for i in range(n_days):
                date = f"{start}+{i}"
                w = call_agent(f"http://127.0.0.1:{WEATHER_PORT}/rpc", "get_weather", {"city":city,"date":date})
                if "result" in w:
                    weather_texts.append(w["result"]["text"])
                else:
                    weather_texts.append(f"weather-error:{w.get('error')}")
            # build prompt for Cohere Chat
            prompt = "Create a {}-day itinerary for {} starting {}.\nWeather:\n{}\nPreferences:{}\n\nProvide a short structured itinerary.".format(n_days,city,start,"\n".join(weather_texts), json.dumps(params.get("preferences",{})))
            # Cohere chat call (ClientV2)
            chat_res = co.chat(model=COHERE_MODEL, messages=[{"role":"system","content":"You are a concise travel planner."},{"role":"user","content":prompt}], max_tokens=400)
            itinerary = chat_res.message.content[0].text
            return jsonrpc_success(rid, {"itinerary": itinerary})
        elif method == "plan_from_structured":
            # receives weather structured objects to make a robust plan
            structured = params.get("weather_structured", [])
            prompt = "Given the following structured weather data:\n{}\nCreate a {}-day plan starting {}.".format(json.dumps(structured,indent=2), params.get("n_days",2), params.get("start_date",""))
            chat_res = co.chat(model=COHERE_MODEL, messages=[{"role":"system","content":"You are a concise travel planner."},{"role":"user","content":prompt}], max_tokens=400)
            return jsonrpc_success(rid, {"itinerary": chat_res.message.content[0].text})
        else:
            return jsonrpc_error(rid, -32601, "method not found")
    except Exception as e:
        return jsonrpc_error(rid, -32000, f"internal: {e}")

def run_planner():
    uvicorn.run(planner_app, host="127.0.0.1", port=PLANNER_PORT, log_level="info")

# Orchestrator: reads agent-cards (local files), calls WeatherAgent then PlannerAgent via JSON-RPC
import threading, time, json, requests, os, uuid, pprint

def orchestrate_sample(city="Chennai", start_date="2025-10-15", n_days=2, preferences=None):
    preferences = preferences or {}
    # discover cards from files
    wcard = json.load(open("agent_card_weatheragent.json")) if os.path.exists("agent_card_weatheragent.json") else {"endpoint": f"http://127.0.0.1:{WEATHER_PORT}/rpc"}
    pcard = json.load(open("agent_card_planneragent.json")) if os.path.exists("agent_card_planneragent.json") else {"endpoint": f"http://127.0.0.1:{PLANNER_PORT}/rpc"}
    # call planner via 'plan_from_weather' (planner will call weather itself)
    payload = {"jsonrpc":"2.0","id": str(uuid.uuid4()), "method":"plan_from_weather", "params":{"city":city,"start_date":start_date,"n_days":n_days,"preferences":preferences}}
    headers = {"Content-Type":"application/json","X-A2A-KEY": os.environ['A2A_API_KEY']}
    r = requests.post(pcard['endpoint'], json=payload, headers=headers, timeout=40)
    pprint.pprint(r.json())
    # save transcript
    with open(f"transcript_{int(time.time())}.json","w") as f:
        json.dump({"request":payload,"response":r.json()}, f, indent=2)
    return r.json()

# no network threads yet — services need to be running

import threading, time

t_w = threading.Thread(target=run_weather, daemon=True)
t_p = threading.Thread(target=run_planner, daemon=True)

t_w.start()
time.sleep(0.6)
t_p.start()
time.sleep(0.6)

print("Weather and Planner started on ports", WEATHER_PORT, PLANNER_PORT)
print("Run orchestrate_sample(...) to invoke the flow (Planner will call Weather via JSON-RPC).")

# Run this after Cell 8 (services up)
res = orchestrate_sample("Bengaluru","2025-10-10", n_days=2, preferences={"budget":"low","interests":["temples","food"]})
print("Orchestration finished. See transcript_*.json saved in runtime.")

# list transcripts and show the latest
import glob, json, pprint
files = sorted(glob.glob("transcript_*.json"))
print("Transcripts found:", files)
if files:
    with open(files[-1]) as f:
        data = json.load(f)
    pprint.pprint(data)

import glob, json
files = sorted(glob.glob("transcript_*.json"))
if not files:
    print("No transcripts found.")
else:
    with open(files[-1]) as f:
        data = json.load(f)
    # Try common nesting: response -> result -> itinerary OR response -> result -> itinerary
    try:
        res = data['response'] if 'response' in data else data['response']
    except Exception:
        res = data.get('response', data)
    # adapt to how your orchestrate_sample saved it
    print("Itinerary (raw):\n")
    print(json.dumps(data, indent=2))

cities = ["Mumbai","Bengaluru","Chennai","Kolkata"]
for c in cities:
    r = orchestrate_sample(city=c, start_date="2025-10-20", n_days=2, preferences={"interests":["food","sightseeing"]})
    print("Done:", c)

def orchestrate_structured(city="Chennai", start_date="2025-10-15", n_days=2, preferences=None):
    prefs = preferences or {}
    payload = {"jsonrpc":"2.0","id": str(uuid.uuid4()), "method":"plan_from_weather", "params":{"city":city,"start_date":start_date,"n_days":n_days,"preferences":prefs, "force_structured": True}}
    headers = {"Content-Type":"application/json","X-A2A-KEY": os.environ['A2A_API_KEY']}
    # call planner endpoint
    pcard = {"endpoint": f"http://127.0.0.1:{PLANNER_PORT}/rpc"}
    r = requests.post(pcard['endpoint'], json=payload, headers=headers, timeout=60)
    jb = r.json()
    # attempt to parse JSON in itinerary if present
    try:
        text = jb['result']['itinerary']
        import re, json
        # find first JSON object in text
        m = re.search(r"\\{[\\s\\S]*\\}", text)
        if m:
            obj = json.loads(m.group())
            return obj
    except Exception:
        pass
    return jb

# Example run
print(orchestrate_structured("Delhi","2025-10-20", n_days=2))

# ---------------- Batch run: create 20 transcripts and save a single JSON ----------------
import requests, json, time, uuid, os, pprint, datetime

# Settings: change if needed
NUM_EXAMPLES = 20
START_DATE_BASE = "2025-10-15"   # base date; we'll offset days per example
OUT_FILE = "batch_itineraries.json"
TIMEOUT = 40

# Make sure required globals exist
try:
    WEATHER_PORT
    PLANNER_PORT
except NameError:
    # fallback to env or defaults used earlier
    WEATHER_PORT = int(os.environ.get('WEATHER_PORT', WEATHER_PORT if 'WEATHER_PORT' in globals() else 8102))
    PLANNER_PORT = int(os.environ.get('PLANNER_PORT', PLANNER_PORT if 'PLANNER_PORT' in globals() else 8103))

# sample cities (20). Edit this list if you want specific cities.
cities = [
    "Mumbai","Delhi","Bengaluru","Chennai","Kolkata",
    "Hyderabad","Pune","Ahmedabad","Jaipur","Lucknow",
    "Surat","Nagpur","Visakhapatnam","Bhopal","Coimbatore",
    "Thiruvananthapuram","Patna","Ludhiana","Vadodara","Goa"
]

# if fewer than NUM_EXAMPLES, repeat/rotate
if len(cities) < NUM_EXAMPLES:
    cities = (cities * ((NUM_EXAMPLES // len(cities)) + 1))[:NUM_EXAMPLES]
else:
    cities = cities[:NUM_EXAMPLES]

batch_results = []

def iso_date_offset(base_iso, offset_days):
    # base_iso expected YYYY-MM-DD
    dt = datetime.datetime.strptime(base_iso, "%Y-%m-%d")
    dt2 = dt + datetime.timedelta(days=offset_days)
    return dt2.strftime("%Y-%m-%d")

for idx, city in enumerate(cities, start=1):
    req_id = str(uuid.uuid4())
    start_date = iso_date_offset(START_DATE_BASE, idx % 7)  # vary start date a bit
    n_days = 2  # or choose 2/3 randomly
    prefs = {"budget": "moderate", "interests": ["sightseeing", "food"]}

    transcript = {
        "request_id": req_id,
        "created_at": datetime.datetime.utcnow().isoformat() + "Z",
        "user_payload": {"city": city, "start_date": start_date, "n_days": n_days, "preferences": prefs},
        "weather_calls": [],
        "planner_call": None
    }

    print(f"[{idx}/{NUM_EXAMPLES}] Processing {city} starting {start_date} ...")

    # 1) Query WeatherAgent structured for each date and record
    weather_structured_list = []
    for di in range(n_days):
        date = f"{start_date}+{di}"
        wreq = {"jsonrpc":"2.0","id": str(uuid.uuid4()), "method":"get_weather_structured", "params":{"city": city, "date": date}}
        headers = {"Content-Type":"application/json", "X-A2A-KEY": os.environ.get('A2A_API_KEY')}

        call_record = {"date": date, "sent_at": datetime.datetime.utcnow().isoformat() + "Z", "request": wreq}
        try:
            r = requests.post(f"http://127.0.0.1:{WEATHER_PORT}/rpc", json=wreq, headers=headers, timeout=10)
            call_record["status_code"] = r.status_code
            try:
                call_record["response"] = r.json()
                # try to extract structured block if the agent returns it under result.structured
                resp_json = call_record["response"]
                structured = None
                if isinstance(resp_json, dict) and resp_json.get("result"):
                    if isinstance(resp_json["result"], dict) and resp_json["result"].get("structured"):
                        structured = resp_json["result"]["structured"]
                    elif isinstance(resp_json["result"], dict) and resp_json["result"].get("text"):
                        structured = {"text": resp_json["result"]["text"]}
                call_record["extracted_structured"] = structured
                weather_structured_list.append(resp_json)
            except Exception as e:
                call_record["response_text"] = r.text
                weather_structured_list.append({"error": "invalid-json-response", "text": r.text})
        except Exception as e:
            call_record["error"] = str(e)
            weather_structured_list.append({"error": str(e)})
        call_record["response_received_at"] = datetime.datetime.utcnow().isoformat() + "Z"
        transcript["weather_calls"].append(call_record)
        # small pause to avoid tight loops
        time.sleep(0.3)

    # 2) Call PlannerAgent with the preloaded structured weather list
    planner_payload = {
        "jsonrpc":"2.0",
        "id": req_id,
        "method":"plan_from_structured",
        "params": {
            "city": city,
            "start_date": start_date,
            "n_days": n_days,
            "preferences": prefs,
            "weather_structured": weather_structured_list
        }
    }
    headers = {"Content-Type":"application/json", "X-A2A-KEY": os.environ.get('A2A_API_KEY')}
    planner_record = {"sent_at": datetime.datetime.utcnow().isoformat() + "Z", "request": planner_payload}
    try:
        pr = requests.post(f"http://127.0.0.1:{PLANNER_PORT}/rpc", json=planner_payload, headers=headers, timeout=TIMEOUT)
        planner_record["status_code"] = pr.status_code
        try:
            planner_record["response"] = pr.json()
        except Exception:
            planner_record["response_text"] = pr.text
    except Exception as e:
        planner_record["error"] = str(e)
    planner_record["response_received_at"] = datetime.datetime.utcnow().isoformat() + "Z"
    transcript["planner_call"] = planner_record

    # 3) Save transcript to list
    batch_results.append(transcript)

    # optional small delay between examples
    time.sleep(0.6)

# Save entire batch file
with open(OUT_FILE, "w") as f:
    json.dump(batch_results, f, indent=2)

print("Batch saved to:", OUT_FILE)
print("Number of transcripts saved:", len(batch_results))